apiVersion: batch/v1
kind: Job
metadata:
  name: tn-job #change this to be more specific
  namespace: cms-ml           
spec:
  template:
    spec:
      containers:
      - name: tn-jetnet-part #change this -> this is the name of your container
        image: pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime  # base image
        command:
        - sh
        - -c
        - |
          cd /opt/repo/YOUR_REPO_PATH && \
          pip install --upgrade pip && \
          pip install numpy pandas matplotlib tqdm scikit-learn seaborn weaver-core jetnet tensorboard && \
          mkdir -p /opt/repo/output && \
          python YOUR_SCRIPT.py              # change to your script
        volumeMounts:
        - name: git-repo 
          mountPath: /opt/repo 
        resources:
          limits:
            memory: "8Gi"
            cpu: "1"
            nvidia.com/gpu: "1"
          requests:
            memory: "8Gi"
            cpu: "1"
            nvidia.com/gpu: "1"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
        - clone
        - --single-branch
        - https://github.com/YOUR_USERNAME/YOUR_REPO.git      # change this
        - /opt/repo/YOUR_REPO_PATH                            # change this
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: "600Mi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "0.5"
      volumes:
      - name: git-repo
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 3
